---
title: "Make_DoReMiTra_Metadata"
author: "Ahmed Hassan"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r}

#' Generate metadata.csv for ExperimentHub submission
#'
#' @param se_list A named list of SummarizedExperiment objects
#' @param rdata_path_base Path relative to inst/extdata where .RDS files will be saved
#' @param source_version Optional, version label for datasets (default = current date)
#' @return A data.frame of metadata written to disk
#' @export
#' 
#' 
generate_experimenthub_metadata <- function(
  se_list,
  rdata_path_base = "DoReMiTra/SE",  # path inside the package
  source_version =""
) {
  metadata_entries <- lapply(names(se_list), function(se_name) {
    se <- se_list[[se_name]]

    # Infer accession
    accession <- stringr::str_extract(se_name, "GSE\\d+")

    # Infer species (can be multiple)
    organisms <- unique(as.character(SummarizedExperiment::colData(se)$Organism))
    species <- paste(sort(organisms), collapse = "; ")

    # Infer radiation type
    if ("Radiation_type" %in% colnames(SummarizedExperiment::colData(se))) {
      rad_types <- unique(SummarizedExperiment::colData(se)$Radiation_type)
      radiation <- paste(sort(rad_types), collapse = "; ")
    } else {
      radiation <- NA
    }

    # Title and Description
    title <- glue::glue("{se_name} expression dataset")
    description <- glue::glue("Processed expression data from GEO series {accession} related to {radiation} exposure.")

    # Metadata row
    data.frame(
      Title = title,
      Description = description,
      RDataPath = file.path(rdata_path_base, paste0(se_name, ".RDS")),
      BiocVersion = "3.21",  # adjust depending on target Bioconductor release
      SourceType = "GSEMatrix",
      SourceUrl = paste0("https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=", accession),
      SourceVersion = as.character(source_version),
      Species = species,
      DataProvider = "GEO",
      TaxonomyId = NA,
      Coordinate_1_based = TRUE,
      Genome = NA,
      Maintainer = "Ahmed Hassan <ahhassan@uni-mainz.de>",
      RDataClass = "SummarizedExperiment",
      DispatchClass = "RDS",
      stringsAsFactors = FALSE
    )
  })

  # Combine and write to file
  DoReMiTra_metadata_df <- do.call(rbind, metadata_entries)
  #readr::write_csv(DoReMiTra_metadata_df, output_path)
  #message("✅ ExperimentHub metadata written to: ", output_path)

  return(DoReMiTra_metadata_df)
}


```

```{r}

metadata <- generate_experimenthub_metadata(
    se_list = all_se_list,
    rdata_path_base = "DoReMiTra/SE"
)

metadata$Description[35]<- "Processed expression data from GitHub repository AhmedSAHassan/Phybion_ShortReads_Analysis related to X-ray exposure."

metadata$SourceType[35]<- "RDS"

#readr::write_csv(DoReMiTra_metadata, "inst/extdata/DoReMiTra_Metadata.csv")


```

```{r}

# since SE_Park_2017_vitro_GSE102971_GPL10332 dataset has 2 species, we will split it into 2 rows in the metadata file

new_row <- data.frame(
  Title = "SE_Park_2017_vitro_GSE102971_GPL10332 expression dataset",
  Description = "Processed expression data from GEO series GSE102971 related to gamma ray exposure.",
  RDataPath = "DoReMiTra/SE/SE_Park_2017_vitro_GSE102971_GPL10332.RDS",
  BiocVersion = "3.21",
  SourceType = "GSEMatrix",
  SourceUrl = "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE102971	",
  SourceVersion = "",
  Species = "Macaca mulatta",
  DataProvider = "GEO",
  TaxonomyId = NA,
  Coordinate_1_based = TRUE,
  Genome = NA,
  Maintainer = "Ahmed Hassan <ahhassan@uni-mainz.de>",
  RDataClass = "SummarizedExperiment",
  DispatchClass = "RDS",
  stringsAsFactors = FALSE
)

metadata <- rbind(DoReMiTra_metadata, new_row)

metadata$Species[4]<- "Homo sapiens"

write.csv(metadata, "inst/extdata/metadata.csv", row.names = FALSE)


```

