
#'Summarize Metadata for a DoReMiTra Dataset
#'
#' @param se The name of the SE object as defined by the user
#'
#' @returns A character string containing a essential information about the dataset metadata
#'
#' @export
#'
#' @importFrom S4Vectors metadata
#' @importFrom glue glue

#' @examples
#' se <- get_DoReMiTra_data("SE_Ghandhi_2018_InVivo_GSE84898_GPL13497")
#' DoReMiTra_se_summary(se)

DoReMiTra_se_summary <- function(se) {
  if (!inherits(se, "SummarizedExperiment")) {
    stop("Input must be a SummarizedExperiment object.")
  }


  meta <- metadata(se)[["DoReMiTra"]]

  author <- meta$Author
  n_samples <- ncol(se)
  species <- meta$Organism
  radiation <- meta$Radiation
  setting <- meta$Setting
  accession <- meta$Accession
  link <- meta$Link

  print(glue::glue(
    "\nThis dataset is generated by: {author}
    Organism(s): {species}
    Radiation Type: {radiation}
    Experiment Setting: {setting}
    Number of Samples: {n_samples}
    Accession: {accession}
    For more information about this study, please check: \n{link}"
  ))

}
